using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using StaffUniformTracker.Models;
using StaffUniformTracker.Patterns;

namespace StaffUniformTracker.Forms;

public partial class ReportsForm : Form
{
    public ReportsForm()
    {
        InitializeComponent();
        _client.Items.Add("(All clients)");
        foreach (var c in UniformTrackingApp.Instance.Clients.All().OrderBy(c => c.Id))
            _client.Items.Add(c);
        _client.SelectedIndex = 0;
        _from.Value = DateTime.Today.AddDays(-30);
        _to.Value = DateTime.Today;
        _genBtn.Click += (_, _) => Generate();
        _saveBtn.Click += (_, _) => SaveAs();
    }
    private string Render()
    {
        var app = UniformTrackingApp.Instance;

        string? clientFilter = (_client.SelectedItem as Client)?.Id;
        var uniforms = app.Uniforms.All()
            .Where(u => clientFilter == null || u.ClientId == clientFilter)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("Staff Uniform Tracking Report");
        sb.AppendLine("=============================");
        sb.AppendLine($"Generated   : {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Period      : {_from.Value:yyyy-MM-dd} to {_to.Value:yyyy-MM-dd}");
        sb.AppendLine($"Generated by: {app.CurrentUser ?? "(unknown)"}");
        sb.AppendLine($"Client      : {clientFilter ?? "(all)"}");
        sb.AppendLine();

        sb.AppendLine($"{"Id",-12} {"Type",-10} {"Client",-8} {"Staff",-12} {"State",-10} {"Washes",6}");
        sb.AppendLine(new string('-', 60));
        foreach (var u in uniforms.OrderBy(u => u.ClientId).ThenBy(u => u.Id))
            sb.AppendLine($"{u.Id,-12} {u.TypeName,-10} {u.ClientId,-8} {u.StaffId ?? "-",-12} {u.State.Name,-10} {u.WashCount,6}");

        sb.AppendLine();
        sb.AppendLine("Totals");
        sb.AppendLine("------");
        sb.AppendLine($"Items in scope : {uniforms.Count}");
        sb.AppendLine($"Total washes   : {uniforms.Sum(u => u.WashCount)}");

        var washEvents = app.Logger.Entries
            .Count(e => e.To == "Cleaned"
                        && e.Timestamp >= _from.Value
                        && e.Timestamp <= _to.Value.AddDays(1));
        sb.AppendLine($"Wash events    : {washEvents} (from audit log within period)");

        return sb.ToString();
    }
    private void Generate()
    {
        try { _output.Text = Render(); }
        catch (Exception ex)
        {
            MessageBox.Show(this, $"Could not generate report:\n{ex.Message}",
                            "Report error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }
    private void SaveAs()
    {
        try
        {
            var content = string.IsNullOrEmpty(_output.Text) ? Render() : _output.Text;
            using var dlg = new SaveFileDialog
            {
                Title = "Save report",
                Filter = "Plain text (*.txt)|*.txt|All files|*.*",
                FileName = $"uniform-report-{DateTime.Now:yyyyMMdd-HHmm}.txt",
            };
            if (dlg.ShowDialog(this) == DialogResult.OK)
            {
                File.WriteAllText(dlg.FileName, content);
                MessageBox.Show(this, $"Saved to:\n{dlg.FileName}",
                    "Saved", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, $"Could not save report:\n{ex.Message}",
                           "Save error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

}

