using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using StaffUniformTracker.Models;
using StaffUniformTracker.Patterns;

namespace StaffUniformTracker.Forms;

public partial class ReportsForm : Form
{
    public ReportsForm()
    {
        InitializeComponent();
        _client.Items.Add("(All clients)");
        foreach (var c in UniformTrackingApp.Instance.Clients.All().OrderBy(c => c.Id))
            _client.Items.Add(c);
        _client.SelectedIndex = 0;
        _from.Value = DateTime.Today.AddDays(-30);
        _to.Value = DateTime.Today;
        _genBtn.Click += (_, _) => Generate();
    }
    private void Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("Staff Uniform Tracking Report");
        sb.AppendLine("=============================");
        sb.AppendLine($"Generated   : {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Period      : {_from.Value:yyyy-MM-dd} to {_to.Value:yyyy-MM-dd}");
        sb.AppendLine($"Generated by: {UniformTrackingApp.Instance.CurrentUser ?? "-"}\n");

        string? f = (_client.SelectedItem as Client)?.Id;
        var us = UniformTrackingApp.Instance.Uniforms.All()
                    .Where(u => f == null || u.ClientId == f)
                    .ToList();
        foreach (var u in us)
            sb.AppendLine($"{u.Id} {u.TypeName} {u.ClientId} {u.StaffId} {u.State.Name} {u.WashCount}");
        sb.AppendLine($"\nItems: {us.Count}, Total washes: {us.Sum(u => u.WashCount)}");

        var ev = UniformTrackingApp.Instance.Logger.Entries
                  .Count(e => e.To == "Cleaned"
                           && e.Timestamp >= _from.Value
                           && e.Timestamp <= _to.Value.AddDays(1));
        sb.AppendLine($"Wash events  : {ev}");
        _output.Text = sb.ToString();
    }
}

